### ISSUE TITLE
This lib is heavily out of date

### ISSUE THREAD

**Issue by ghost** [DxCx/webpack-istanbul-plugin#2]
Please update dependenices and readme with instructions for Webpack 2.0, can't use this lib now.

**Comment by sukrosono** [comment]
how this differ with [istanbul-instrumenter-loader](https://www.npmjs.com/package/istanbul-instrumenter-loader) ?

**Comment by ghost** [comment]
@brutalcrozt istanbul-instrumenter-loader seems to have dependencies up to date and last changed 4 month ago. But anyway this webpack-istanbul-plugin lib is obsolete for webpack, because there good working instruction https://github.com/zinserjan/mocha-webpack/blob/master/docs/guides/code-coverage.md

I think this lib should be updated saying it is deprecated and link to that instruction.

**Comment by DxCx** [comment]
hey,
im not sure what there are out there today,
but when i tried to use istanbul with webpack, it did not instrument all the files that were running through webpack, but only the files that was actually running got counted.
so i digged in and found out why it happens, and this library was the result of that.
it might be old by now since i haven't used it for long time and also it didn't look like anyone else uses it.
is istanbul-instrumenter-loader will instrument all files properly?

**Comment by ghost** [comment]
That new way according to instructions working good, checked in my project.
